# Generated by Django 3.1.13 on 2021-12-25 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('artiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='songs', to=settings.AUTH_USER_MODEL)),
                ('featured_artistes', models.ManyToManyField(blank=True, null=True, related_name='collabs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='genre',
            name='songs',
            field=models.ManyToManyField(related_name='genre', to='songs.Song'),
        ),
    ]
