# Generated by Django 3.1.13 on 2021-12-25 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0002_auto_20211225_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='genre', to='songs.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='featured_artistes',
            field=models.ManyToManyField(blank=True, related_name='collabs', to=settings.AUTH_USER_MODEL),
        ),
    ]
