# Generated by Django 3.1.13 on 2021-12-27 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('artiste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='songs', to=settings.AUTH_USER_MODEL)),
                ('featured_artistes', models.ManyToManyField(blank=True, related_name='collabs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('songs', models.ManyToManyField(blank=True, related_name='genre', to='songs.Song')),
            ],
        ),
    ]
