# Generated by Django 3.1.13 on 2021-12-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211227_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_last_edited',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
