# Generated by Django 3.1.13 on 2021-12-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20211227_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='time_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
